#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# dnsmasq-ha UI installer (operator's laptop).
#
# One-command setup:
#
#   curl -fsSL https://raw.githubusercontent.com/taiojia/dnsmasq-ha/master/scripts/install-ui.sh | bash
#
# Arguments (when piping, pass them via `bash -s --`, e.g.):
#   curl -fsSL <url> | bash -s -- --port 4173
#
# Flags:
#   --port <port>   Local preview port (default 4173)
#   --dir <path>    Install directory (default ~/.dnsmasq-ha)
#   --ref <ref>     Branch or tag to install (default master)
#   --uninstall     Remove the launcher
#   --purge         With --uninstall: also delete the install directory
#   --help          Show this help
#
# The script is idempotent: re-running it updates the installation.
# -----------------------------------------------------------------------------
set -euo pipefail

REPO_URL="https://github.com/taiojia/dnsmasq-ha.git"
INSTALL_DIR="${HOME}/.dnsmasq-ha"
REF="master"
PORT="4173"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/dnsmasq-ha-ui"
UNINSTALL=0
PURGE=0
NODE_MAJOR=18
NODESOURCE_SETUP="https://deb.nodesource.com/setup_20.x"

log()  { printf '\033[1;34m[install-ui]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[install-ui]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[install-ui]\033[0m %s\n' "$*" >&2; exit 1; }

usage() { sed -n '2,/^# -----------------------------------------------------------------------------$/p' "$0"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --port)      PORT="${2:?--port requires a value}"; shift 2 ;;
    --dir)       INSTALL_DIR="${2:?--dir requires a value}"; shift 2 ;;
    --ref)       REF="${2:?--ref requires a value}"; shift 2 ;;
    --uninstall) UNINSTALL=1; shift ;;
    --purge)     PURGE=1; shift ;;
    --help|-h)   usage; exit 0 ;;
    *)           die "unknown argument: $1 (see --help)" ;;
  esac
done

# -----------------------------------------------------------------------------
# Uninstall
# -----------------------------------------------------------------------------
if [ "$UNINSTALL" -eq 1 ]; then
  log "removing launcher ${LAUNCHER}..."
  rm -f "$LAUNCHER"
  if [ "$PURGE" -eq 1 ]; then
    log "removing install directory ${INSTALL_DIR}..."
    rm -rf "$INSTALL_DIR"
  else
    warn "install directory kept: ${INSTALL_DIR} (re-run with --purge to delete)"
  fi
  log "uninstalled."
  exit 0
fi

# -----------------------------------------------------------------------------
# Preflight: Node.js >= 18
# -----------------------------------------------------------------------------
node_major() {
  command -v node >/dev/null 2>&1 || { echo 0; return; }
  node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0
}

install_node_linux() {
  log "installing Node.js 20.x via NodeSource..."
  command -v sudo >/dev/null 2>&1 || die "sudo required to install Node.js"
  if ! command -v curl >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install -y curl ca-certificates
  fi
  curl -fsSL "$NODESOURCE_SETUP" | sudo -E bash -
  sudo apt-get install -y nodejs
}

install_node_macos() {
  command -v brew >/dev/null 2>&1 || die "Node.js >= ${NODE_MAJOR} is required; install it with: brew install node"
  log "installing Node.js via Homebrew..."
  brew install node
}

if [ "$(node_major)" -lt "$NODE_MAJOR" ]; then
  case "$(uname -s)" in
    Linux) install_node_linux ;;
    Darwin) install_node_macos ;;
    *) die "unsupported OS; install Node.js >= ${NODE_MAJOR} manually" ;;
  esac
fi
command -v npm >/dev/null 2>&1 || die "npm not found after Node.js installation"
command -v git >/dev/null 2>&1 || die "git is required (https://git-scm.com)"

# -----------------------------------------------------------------------------
# Fetch / update the source
# -----------------------------------------------------------------------------
if [ -d "${INSTALL_DIR}/.git" ]; then
  log "updating existing checkout at ${INSTALL_DIR} (ref: ${REF})..."
  git -C "$INSTALL_DIR" fetch --force origin "$REF"
  git -C "$INSTALL_DIR" checkout -f FETCH_HEAD
else
  log "cloning ${REPO_URL} (ref: ${REF}) into ${INSTALL_DIR}..."
  rm -rf "$INSTALL_DIR"
  git clone --depth 1 --branch "$REF" "$REPO_URL" "$INSTALL_DIR"
fi

log "installing dependencies (npm ci)..."
npm ci --no-audit --no-fund --prefix "$INSTALL_DIR"

log "building UI..."
npm run build --prefix "$INSTALL_DIR"

# -----------------------------------------------------------------------------
# Launcher
# -----------------------------------------------------------------------------
log "writing launcher ${LAUNCHER}..."
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<LAUNCHER
#!/usr/bin/env bash
# dnsmasq-ha management UI (generated by scripts/install-ui.sh)
cd "${INSTALL_DIR}" || exit 1
( sleep 2; xdg-open "http://127.0.0.1:${PORT}" >/dev/null 2>&1 || open "http://127.0.0.1:${PORT}" >/dev/null 2>&1 || true ) &
exec npm run preview -w @dnsmasq-ha/ui -- --host 127.0.0.1 --port ${PORT} --strictPort
LAUNCHER
chmod +x "$LAUNCHER"

case ":${PATH}:" in
  *":${BIN_DIR}:"*) ;;
  *) warn "${BIN_DIR} is not in your PATH; add it: export PATH=\"\${PATH}:${BIN_DIR}\"" ;;
esac

log "-------------------------------------------"
log "dnsmasq-ha UI installed."
log "  start : dnsmasq-ha-ui"
log "  url   : http://127.0.0.1:${PORT} (opens automatically)"
log "  data  : ${INSTALL_DIR}"
log "Uninstall anytime: this script --uninstall [--purge]"
log "-------------------------------------------"
